kind: pipeline
type: docker
name: default

steps:

- name: setup cluster
  image: kameshsampath/kube-dev-tools:0.1.0
  pull: never
  commands:
    - ./hack/setup.sh
  volumes:
    - name: docker-sock
      path: /var/run/docker.sock 

- name: install istio
  image: kameshsampath/kube-dev-tools:0.1.0
  commands:
    - k3d kubeconfig get $K3D_CLUSTER_NAME > $KUBECONFIG
    - chmod 0700 $KUBECONFIG
    - helm repo add istio https://istio-release.storage.googleapis.com/charts
    - helm repo update
    - kubectl create namespace istio-system || true
    - helm upgrade --install istio-base istio/base -n istio-system
    - helm upgrade --install istiod istio/istiod -n istio-system --wait
    - kubectl create namespace istio-ingress || true
    - kubectl label namespace istio-ingress istio-injection=enabled --overwrite=true
    - helm upgrade --install istio-ingress istio/gateway -n istio-ingress
  volumes:
    - name: docker-sock
      path: /var/run/docker.sock 

- name: protoc-server
  image: kameshsampath/protoc-go
  commands:
  - mkdir -p pkg/greeter
  - |
   protoc -I ./protos greeter.proto \
   --go_out=./pkg/greeter --go-grpc_out=./pkg/greeter \
   --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative

## TODO this not working why???
- name: deploy server
  image: kameshsampath/kube-dev-tools:0.1.0
  commands:
    - k3d kubeconfig get $K3D_CLUSTER_NAME > $KUBECONFIG
    - chmod 0700 $KUBECONFIG
    - kubectl create ns demos || true
    - kubectl label ns demos istio-injection=enabled --overwrite=true
    - kubens demos
    - ko create --insecure-registry -f config
    # simple docker pull and pushes works
    # - docker pull busybox:latest
    # - docker tag nginx:latest $KO_DOCKER_REPO/busybox:latest
    # - docker push $KO_DOCKER_REPO/busybox:latest
  volumes:
    - name: docker-sock
      path: /var/run/docker.sock

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
   