apiVersion: v1
kind: Pod
metadata:
  annotations:
    inject.istio.io/templates: grpc-agent
    kubectl.kubernetes.io/default-container: greeter
    kubectl.kubernetes.io/default-logs-container: greeter
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
    proxy.istio.io/overrides: '{"containers":[{"name":"greeter","image":"k3d-istio-grpc-demo-registry.localhost:5001/greeter/server-2203a6e2aa1662aceac218edae976ed5@sha256:4ed4597f87d1a4c84943c5c948b662a9defbc5f83fc26330efdc599f51d943f1","ports":[{"containerPort":9090,"protocol":"TCP"}],"resources":{"limits":{"cpu":"500m","memory":"128Mi"},"requests":{"cpu":"500m","memory":"128Mi"}},"volumeMounts":[{"name":"kube-api-access-x75td","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}]}'
    sidecar.istio.io/rewriteAppHTTPProbers: "false"
    sidecar.istio.io/status: '{"initContainers":null,"containers":["istio-proxy","greeter"],"volumes":["workload-socket","workload-certs","istio-xds","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}'
  creationTimestamp: "2022-11-17T09:06:46Z"
  generateName: greeter-6cbf496cf8-
  labels:
    app: greeter
    pod-template-hash: 6cbf496cf8
    service.istio.io/canonical-name: greeter
    service.istio.io/canonical-revision: latest
  name: greeter-6cbf496cf8-v6st4
  namespace: demos
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: greeter-6cbf496cf8
    uid: 05e46f30-740f-4792-9362-c1ad48e06d61
  resourceVersion: "4608"
  uid: f52e4aa9-35e8-445c-9612-d8375bc197ac
spec:
  containers:
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=default:info
    env:
    - name: ISTIO_META_GENERATOR
      value: grpc
    - name: OUTPUT_CERTS
      value: /var/lib/istio/data
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: CA_ADDR
      value: istiod.istio-system.svc:15012
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: PROXY_CONFIG
      value: |
        {"holdApplicationUntilProxyStarts":true}
    - name: ISTIO_META_POD_PORTS
      value: |-
        [
            {"containerPort":9090,"protocol":"TCP"}
        ]
    - name: ISTIO_META_APP_CONTAINERS
      value: greeter
    - name: ISTIO_META_CLUSTER_ID
      value: Kubernetes
    - name: ISTIO_META_WORKLOAD_NAME
      value: greeter
    - name: ISTIO_META_OWNER
      value: kubernetes://apis/apps/v1/namespaces/demos/deployments/greeter
    - name: ISTIO_META_MESH_ID
      value: cluster.local
    - name: TRUST_DOMAIN
      value: cluster.local
    - name: ISTIO_META_DNS_CAPTURE
      value: "false"
    - name: DISABLE_ENVOY
      value: "true"
    image: docker.io/istio/proxyv2:1.16.0
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
          - pilot-agent
          - wait
          - --url=http://localhost:15020/healthz/ready
    name: istio-proxy
    ports:
    - containerPort: 15020
      name: mesh-metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /healthz/ready
        port: 15020
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/workload-spiffe-uds
      name: workload-socket
    - mountPath: /var/run/secrets/workload-spiffe-credentials
      name: workload-certs
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-xds
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-x75td
      readOnly: true
  - env:
    - name: GRPC_XDS_EXPERIMENTAL_SECURITY_SUPPORT
      value: "true"
    - name: GRPC_XDS_BOOTSTRAP
      value: /etc/istio/proxy/grpc-bootstrap.json
    image: k3d-istio-grpc-demo-registry.localhost:5001/greeter/server-2203a6e2aa1662aceac218edae976ed5@sha256:4ed4597f87d1a4c84943c5c948b662a9defbc5f83fc26330efdc599f51d943f1
    imagePullPolicy: IfNotPresent
    name: greeter
    ports:
    - containerPort: 9090
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-xds
    - mountPath: /var/run/secrets/workload-spiffe-credentials
      name: workload-certs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-x75td
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3d-istio-grpc-demo-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: workload-socket
  - emptyDir: {}
    name: workload-certs
  - emptyDir:
      medium: Memory
    name: istio-xds
  - emptyDir: {}
    name: istio-data
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: istio-podinfo
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
    name: istiod-ca-cert
  - name: kube-api-access-x75td
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-11-17T09:06:46Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-11-17T09:06:47Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-11-17T09:06:47Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-11-17T09:06:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://2537a9d0239b2a4d74229197e272cef8abfff28e2eb333f7922bde182ce6e19c
    image: sha256:0740ba964debff57b79eb300d55f9527951db334e0f2262e8ba0300d7a5b6bca
    imageID: k3d-istio-grpc-demo-registry.localhost:5001/greeter/server-2203a6e2aa1662aceac218edae976ed5@sha256:4ed4597f87d1a4c84943c5c948b662a9defbc5f83fc26330efdc599f51d943f1
    lastState: {}
    name: greeter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-11-17T09:06:47Z"
  - containerID: containerd://98489f433b2cbcc4d8cd4ed1e152a0b51305536d4d3860cf2e11661344a0e980
    image: docker.io/istio/proxyv2:1.16.0
    imageID: docker.io/istio/proxyv2@sha256:f6f97fa4fb77a3cbe1e3eca0fa46bd462ad6b284c129cf57bf91575c4fb50cf9
    lastState: {}
    name: istio-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-11-17T09:06:46Z"
  hostIP: 192.168.224.4
  phase: Running
  podIP: 10.42.0.16
  podIPs:
  - ip: 10.42.0.16
  qosClass: Burstable
  startTime: "2022-11-17T09:06:46Z"
