apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: greeter
    kubectl.kubernetes.io/default-logs-container: greeter
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
    sidecar.istio.io/status: '{"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["workload-socket","credential-socket","workload-certs","istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}'
  creationTimestamp: "2022-11-17T09:07:25Z"
  generateName: greeter-874cd486c-
  labels:
    app: greeter
    pod-template-hash: 874cd486c
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: greeter
    service.istio.io/canonical-revision: latest
  name: greeter-874cd486c-mfqrx
  namespace: demos
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: greeter-874cd486c
    uid: 1d944873-d1c3-449f-ad85-845b4846e1e8
  resourceVersion: "4713"
  uid: f7c7546c-cdf2-4ef3-bda9-6ed3f8836a1b
spec:
  containers:
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=default:info
    - --concurrency
    - "2"
    env:
    - name: JWT_POLICY
      value: third-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: CA_ADDR
      value: istiod.istio-system.svc:15012
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: PROXY_CONFIG
      value: |
        {"holdApplicationUntilProxyStarts":true}
    - name: ISTIO_META_POD_PORTS
      value: |-
        [
            {"containerPort":9090,"protocol":"TCP"}
        ]
    - name: ISTIO_META_APP_CONTAINERS
      value: greeter
    - name: ISTIO_META_CLUSTER_ID
      value: Kubernetes
    - name: ISTIO_META_INTERCEPTION_MODE
      value: REDIRECT
    - name: ISTIO_META_WORKLOAD_NAME
      value: greeter
    - name: ISTIO_META_OWNER
      value: kubernetes://apis/apps/v1/namespaces/demos/deployments/greeter
    - name: ISTIO_META_MESH_ID
      value: cluster.local
    - name: TRUST_DOMAIN
      value: cluster.local
    image: docker.io/istio/proxyv2:1.16.0
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
          - pilot-agent
          - wait
    name: istio-proxy
    ports:
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/workload-spiffe-uds
      name: workload-socket
    - mountPath: /var/run/secrets/credential-uds
      name: credential-socket
    - mountPath: /var/run/secrets/workload-spiffe-credentials
      name: workload-certs
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hcl4m
      readOnly: true
  - image: k3d-istio-grpc-demo-registry.localhost:5001/greeter/server-2203a6e2aa1662aceac218edae976ed5@sha256:4ed4597f87d1a4c84943c5c948b662a9defbc5f83fc26330efdc599f51d943f1
    imagePullPolicy: IfNotPresent
    name: greeter
    ports:
    - containerPort: 9090
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 500m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hcl4m
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - istio-iptables
    - -p
    - "15001"
    - -z
    - "15006"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - '*'
    - -x
    - ""
    - -b
    - '*'
    - -d
    - 15090,15021,15020
    - --log_output_level=default:info
    image: docker.io/istio/proxyv2:1.16.0
    imagePullPolicy: IfNotPresent
    name: istio-init
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hcl4m
      readOnly: true
  nodeName: k3d-istio-grpc-demo-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: workload-socket
  - emptyDir: {}
    name: credential-socket
  - emptyDir: {}
    name: workload-certs
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - emptyDir: {}
    name: istio-data
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: istio-podinfo
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
    name: istiod-ca-cert
  - name: kube-api-access-hcl4m
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-11-17T09:07:26Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-11-17T09:07:25Z"
    message: 'containers with unready status: [greeter]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-11-17T09:07:25Z"
    message: 'containers with unready status: [greeter]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-11-17T09:07:25Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://9a28469dedb511c3d50136c286147541b361b967b8adbfc558abde061f990230
    image: sha256:0740ba964debff57b79eb300d55f9527951db334e0f2262e8ba0300d7a5b6bca
    imageID: k3d-istio-grpc-demo-registry.localhost:5001/greeter/server-2203a6e2aa1662aceac218edae976ed5@sha256:4ed4597f87d1a4c84943c5c948b662a9defbc5f83fc26330efdc599f51d943f1
    lastState:
      terminated:
        containerID: containerd://190326d8f09c714a3c3c1de7a157ba60ad91c4b3b9ca9c8b8403087f7b576918
        exitCode: 1
        finishedAt: "2022-11-17T09:07:28Z"
        reason: Error
        startedAt: "2022-11-17T09:07:28Z"
    name: greeter
    ready: false
    restartCount: 2
    started: false
    state:
      terminated:
        containerID: containerd://9a28469dedb511c3d50136c286147541b361b967b8adbfc558abde061f990230
        exitCode: 1
        finishedAt: "2022-11-17T09:07:44Z"
        reason: Error
        startedAt: "2022-11-17T09:07:44Z"
  - containerID: containerd://41fa3af6f8e8d8643fd479b1f6f1e2f825adb69154a46e0134f6e57392b9aadc
    image: docker.io/istio/proxyv2:1.16.0
    imageID: docker.io/istio/proxyv2@sha256:f6f97fa4fb77a3cbe1e3eca0fa46bd462ad6b284c129cf57bf91575c4fb50cf9
    lastState: {}
    name: istio-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-11-17T09:07:26Z"
  hostIP: 192.168.224.4
  initContainerStatuses:
  - containerID: containerd://ce1d1954fc85793fcda5ec7c77558dbeecb8fe50f493f8f9370c6f1229ad4b81
    image: docker.io/istio/proxyv2:1.16.0
    imageID: docker.io/istio/proxyv2@sha256:f6f97fa4fb77a3cbe1e3eca0fa46bd462ad6b284c129cf57bf91575c4fb50cf9
    lastState: {}
    name: istio-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://ce1d1954fc85793fcda5ec7c77558dbeecb8fe50f493f8f9370c6f1229ad4b81
        exitCode: 0
        finishedAt: "2022-11-17T09:07:26Z"
        reason: Completed
        startedAt: "2022-11-17T09:07:26Z"
  phase: Running
  podIP: 10.42.0.17
  podIPs:
  - ip: 10.42.0.17
  qosClass: Burstable
  startTime: "2022-11-17T09:07:25Z"
