apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-v2
spec:
  selector:
    matchLabels:
      app: greeter
      version: v2
  template:
    metadata:
      annotations:
        inject.istio.io/templates: grpc-agent
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
      labels:
        app: greeter
        version: v2
    spec:
      containers:
      - name: greeter
        image: ${PLUGIN_REPO}
        env:
          - name: VERSION
            value: v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
          protocol: TCP
